name: AI PR Reviewer

on:
  pull_request:
    types: [opened, synchronize]

permissions: write-all

jobs:
  ai-pr-reviewer:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: code-diff-bat
        shell: cmd
        run: git_diff.bat

      - name: upload-review-artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-diff-bat
          path: review_output.txt
